#!/bin/bash

#      _____                _  _
#  ___|___ / _ __ _____   _| || |
# / __| |_ \| '_ ` _ \ \ / / || |_
# \__ \___) | | | | | \ V /|__   _|
# |___/____/|_| |_| |_|\_/    |_|

# Time zone
ln -sf /usr/share/zoneinfo/Europe/Amsterdam /etc/localtime

# Localization
sed -i 's/#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/g' /etc/locale.gen
locale-gen
echo "LANG=en_US.UTF-8" > /etc/locale.conf
echo "KEYMAP=dvorak-programmer" > /etc/vconsole.conf

# Network configuration
echo "archlinux" > /etc/hostname
systemctl enable NetworkManager.service

# Root password
echo -e "arch\narch" | passwd

# Boot loader
efibootmgr --create --disk $disk --part 1 --label "Arch Linux" --loader /vmlinuz-linux --unicode "root=$root resume=$swap rw initrd=\intel-ucode.img initrd=\initramfs-linux.img"

# Add a user
useradd -m -G wheel -s /bin/zsh $username
echo -e "arch\narch" | passwd $username
sed -i 's/# %wheel ALL=(ALL:ALL) NOPASSWD: ALL/%wheel ALL=(ALL:ALL) NOPASSWD: ALL/g' /etc/sudoers

# Audio
systemctl start pipewire-pulse.service

# Install suckless tools
mkdir /home/$username/.config
cd /home/$username/.config
for tool in dwm st dwmblocks; do
    git clone "https://github.com/s3mv4/$tool" 
    cd $tool
    sudo make install
    make clean && rm -f config.h blocks.h
    cd ..
done
mkdir -p /home/$username/.local/share/fonts
cp /home/$username/.config/dwm/fonts/* /home/$username/.local/share/fonts/
ln -s /home/$username/.config/dwmblocks/scripts/* /home/$username/.local/bin/
for tool in dmenu slock; do
    git clone "https://git.suckless.org/$tool" 
    cd $tool
    sudo make install
    make clean && rm -f config.h
    cd ..
done

# Deploy ~/.dotfiles
cd /home/$username
git clone https://github.com/s3mv4/.dotfiles
for dotfile in .xinitrc .zshrc .zshenv .zprofile .config/nvim .config/picom; do
    ln -s /home/$username/.dotfiles/$dotfile /home/$username/$dotfile
done
git clone --depth 1 https://github.com/wbthomason/packer.nvim\
 /home/$username/.local/share/nvim/site/pack/packer/start/packer.nvim

# Chown
chown -R $username:$username /home/$username
