#!/bin/bash

#      _____                _  _
#  ___|___ / _ __ _____   _| || |
# / __| |_ \| '_ ` _ \ \ / / || |_
# \__ \___) | | | | | \ V /|__   _|
# |___/____/|_| |_| |_|\_/    |_|

# Config
echo -n "Swap size: "
read swap_size
echo -n "Username: "
read username

# Partition the disks
disk=$(fdisk -l | awk 'NR == 1 {print substr($2, 1, length($2)-1)}')
if [[ $disk =~ "nvme" ]]; then
    esp=${disk}p1
    swap=${disk}p2
    root=${disk}p3
else
    esp=${disk}1
    swap=${disk}2
    root=${disk}3
fi

wipefs -a $disk

(
echo "g"
echo "n"
echo "1"
echo ""
echo "+128M"
echo "t"
echo "1"
echo "n"
echo "2"
echo ""
echo "+$swap_size"
echo "t"
echo "2"
echo "19"
echo "n"
echo "3"
echo ""
echo ""
echo "w"
) | fdisk $disk

# Format the partitions
mkfs.ext4 $root
mkswap $swap
mkfs.fat -F 32 $esp

# Mount the file systems
mount $root /mnt
mount --mkdir $esp /mnt/boot
swapon $swap

# Install essential packages
product_family=$(cat /sys/devices/virtual/dmi/id/product_family)
if [[ $product_family == "Surface" ]]; then
    pacstrap -K /mnt base linux linux-firmware linux-firmware-marvell intel-ucode networkmanager vim man sudo xorg-server xorg-xinit xorg-setxkbmap xorg-xset pipewire pipewire-audio pipewire-pulse feh picom git libxft libxinerama neovim zsh zsh-autosuggestions zsh-syntax-highlighting
else
    pacstrap -K /mnt base linux linux-firmware intel-ucode networkmanager vim man sudo xorg-server xorg-xinit xorg-setxkbmap xorg-xset pipewire pipewire-audio pipewire-pulse feh picom git libxft libxinerama neovim zsh zsh-autosuggestions zsh-syntax-highlighting
fi

# Fstab
genfstab -U /mnt >> /mnt/etc/fstab

# Chroot
export disk
export root
export swap
export username
arch-chroot /mnt ./chroot
