#!/bin/bash

#      _____                _  _
#  ___|___ / _ __ _____   _| || |
# / __| |_ \| '_ ` _ \ \ / / || |_
# \__ \___) | | | | | \ V /|__   _|
# |___/____/|_| |_| |_|\_/    |_|

# Config
echo -n "Swap size: "
read swap_size
echo -n "Username: "
read username

# Partition the disks
disk=$(fdisk -l | awk 'NR == 1 {print substr($2, 1, length($2)-1)}')
if [[ $disk =~ "nvme" ]]; then
    esp=${disk}p1
    swap=${disk}p2
    root=${disk}p3
else
    esp=${disk}1
    swap=${disk}2
    root=${disk}3
fi

fdisk $disk << EOF
g
n
1

+128M
t
1
n
2

+$swap_size
t
2
19
n
3


w
EOF

# Format the partitions
mkfs.ext4 $root
mkswap $swap
mkfs.fat -F 32 $esp

# Mount the file systems
mount $root /mnt
mount --mkdir $esp /mnt/boot
swapon $swap

# Install essential packages
product_family=$(cat /sys/devices/virtual/dmi/id/product_family)
if [[ $product_family == "Surface" ]]; then
    pacstrap -K /mnt base linux linux-firmware linux-firmware-marvell efibootmgr intel-ucode networkmanager vim man sudo xorg-server xorg-xinit xorg-setxkbmap xorg-xset pipewire pipewire-audio pipewire-pulse feh picom git libxft libxinerama make gcc pkgconf scrot brightnessctl iw neovim zsh zsh-autosuggestions zsh-syntax-highlighting
else
    pacstrap -K /mnt base linux linux-firmware efibootmgr intel-ucode networkmanager vim man sudo xorg-server xorg-xinit xorg-setxkbmap xorg-xset pipewire pipewire-audio pipewire-pulse feh picom git libxft libxinerama make gcc pkgconf scrot brightnessctl iw neovim zsh zsh-autosuggestions zsh-syntax-highlighting
fi

# Fstab
genfstab -U /mnt >> /mnt/etc/fstab

# Chroot
cp chroot /mnt/
export disk
export root
export swap
export username
arch-chroot /mnt ./chroot
